### ISSUE TITLE
Error with generating self-signed certs

### ISSUE THREAD

**Issue by Galiullinko** [twitchdev/extensions-samples#2]
When I tried to generate certs, an error occurred
```
./generate_local_ssl.sh: line 10: syntax error near unexpected token `('
./generate_local_ssl.sh: line 10: `  -config <( cat $( [[ "Darwin" -eq "$(uname -s)" ]]  && echo /System/Library/OpenSSL/openssl.cnf || echo /etc/ssl/openssl.cnf  ) \'
```
I'm not strong in shell scripts, so I couldn't solve this problem.

**Comment by d0p3t** [comment]
Some shells don't support Process substitution. Running this script in `/bin/bash` will not give these errors.

More info [here](https://unix.stackexchange.com/questions/151911/syntax-error-near-unexpected-token)

**Comment by Galiullinko** [comment]
@d0p3t thanks a lot, it works
