### ISSUE TITLE
After 'docker-compose up --build', how do I debug this extension if I am running it locally?

### ISSUE THREAD

**Issue by jmb-mage** [twitchdev/extensions-samples#5]
I apologize if this question is just me not reading everything in the docs, but after I run

`docker-compose up --build`

I get (clipped end of output for brevity)

```
Step 8/8 : CMD ./entrypoint.sh
 ---> Using cache
 ---> f25c3fd18a36
Successfully built f25c3fd18a36
Successfully tagged boilerplate_boilerplatebackend:latest
Starting boilerplate_boilerplatebackend_1 ...
Starting boilerplate_boilerplatebackend_1 ... done
Attaching to boilerplate_boilerplatebackend_1
boilerplatebackend_1  |
boilerplatebackend_1  | Running node-supervisor with
boilerplatebackend_1  |   program 'boilerplate.js'
boilerplatebackend_1  |   --watch '.'
boilerplatebackend_1  |   --extensions 'node,js'
boilerplatebackend_1  |   --exec 'node'
boilerplatebackend_1  |
boilerplatebackend_1  | Starting child process with 'node boilerplate.js'
boilerplatebackend_1  | Watching directory '/boilerplate/backend' for changes.
boilerplatebackend_1  | Press rs for restarting the process.
boilerplatebackend_1  | **** DIR NAME /boilerplate/backend
boilerplatebackend_1  | Extension Boilerplate service running on https 8080
```

...and now what?  How do I debug this extension if I am running it locally?  It seems I would need a local copy of the Twitch app?

**Comment by jmb-mage** [comment]
Ok, re-read the docs again and found this:

> While your extension is in Local Test or Hosted Test mode, only viewers on the testing whitelist can see it.

If I am streaming, and I am viewing my stream, I should see the extension?  Or do I still need to be on the whitelist?

I am expecting that I will see this, because it's in the HTML markup for frontend/viewer.html:

`<p>This is the viewer page!</p>`

But I'm not seeing anything different viewing my stream. :(

**Comment by afeng5853** [comment]
Are you using Docker Toolbox?

I had the same exact problem with Docker Toolbox and then I found out that the testing base URL should not be localhost and instead should usually be 192.168.99.100, the default IP of the virtual machine. 

You can check the IP of the virtual machine through `$docker-machine ip`

If you're not using Docker Toolbox run
`docker-compose up --build`
and connect to https://localhost:8080/viewer.html?anchor=video_overlay&language=en-US&mode=viewer on a browser

This is what shows up in the video player (you can use inspect element to check this)

Check what type of error you're getting
