### ISSUE TITLE
Service 'boilerplatebackend' failed to build

### ISSUE THREAD

**Issue by colshacol** [twitchdev/extensions-samples#6]
**Expected**: It to work.

**Actual**: It didn't work.

```
Docker version 17.06.2-ce, build cec0b72
```

<img width="1184" alt="screen shot 2017-09-24 at 1 32 20 am" src="https://user-images.githubusercontent.com/19484365/30780090-5565c960-a0c8-11e7-93a0-8abd14e81439.png">

I am not too well versed in Docker, so it may be obvious to another set of eyes. But I followed the instructions to the t, and this is actually a fresh admin account on this Mac with only a few programs and Docker installed.

**Comment by jmb-mage** [comment]
You do have NodeJS installed and in the path?
