### ISSUE TITLE
net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by Syntaf** [twitchdev/extensions-samples#7]
for some reason, it seems running this extension-sample has suddenly stopped working. I searched all around my extension manager dashboard but found nothing about installing any certificates. Currently, If I do the standard

```
cd extensions-samples/boilerplate
sudo docker-compose up --build
```

then visit my livestream (with the extension installed and in local test mode), I receive `net::ERR_INSECURE_RESPONSE`. Running this worked fine last week, but has seemed to stop working now. Did I change something in my extension manager to cause this?

**Comment by travistyoj** [comment]
Sorry I wasn't able to answer your question.  Are you still stuck on this?  If so, please post questions on the Extensions sections of the Twitch forums at https://discuss.dev.twitch.tv/c/extensions
